# python auto complete
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

# python syntax and style check
[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'
hook_source = '''
    let g:flake8_quickfix_height=7
    let g:flake8_show_in_gutter=1
    let g:flake8_show_in_file=1
    let g:syntastic_python_flake8_args='--ignore=E501,E225'
    autocmd BufWritePost *.py call Flake8()
'''

# python linter
[[plugins]]
repo = 'w0rp/ale'
on_ft = 'python'
hook_source = '''
    let g:ale_linters = {'python': ['flake8']}
    let g:ale_fixers = {'python': ['autopep8', 'black', 'isort']}

    let g:ale_python_flake8_executable = g:python3_host_prog
    let g:ale_python_flake8_options = '-m flake8'

    let g:ale_python_autopep8_executable = g:python3_host_prog
    let g:ale_python_autopep8_options = '-m autopep8'

    let g:ale_python_isort_executable = g:python3_host_prog
    let g:ale_python_isort_options = '-m isort'
    
    let g:ale_fix_on_save = 1
    let g:ale_sign_column_always = 1
    let g:ale_lint_on_enter = 0
    let g:ale_lint_on_save = 1
    let g:ale_lint_on_text_changed = 'never'
    let g:ale_sign_error = '!!' 
    let g:ale_sign_warning = '=='

    nmap <silent> <Space>k <Plug>(ale_previous_wrap)
    nmap <silent> <Space>j <Plug>(ale_next_wrap)
'''

# markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_source = '''
    let g:vim_markdown_folding_disabled = 1
'''
